#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define ONESHOT_TAP_TOGGLE 2

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 5000

#define PERMISSIVE_HOLD

#define COMBO_TERM 20

#undef RGB_MATRIX_HUE_STEP
#define RGB_MATRIX_HUE_STEP 4

#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_MODIFIERS
#define USB_POLLING_INTERVAL_MS 10
#define SERIAL_NUMBER "yX3er/XbQL76"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 5

#define RGB_MATRIX_STARTUP_SPD 60

#define COMBO_ONLY_FROM_LAYER 1

