#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define ONESHOT_TAP_TOGGLE 2

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 2500

#define PERMISSIVE_HOLD

#define COMBO_TERM 35

#undef RGB_MATRIX_HUE_STEP
#define RGB_MATRIX_HUE_STEP 4

#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_MODIFIERS
#define USB_POLLING_INTERVAL_MS 10
#define SERIAL_NUMBER "jmBzJ/jZmOe7"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 12

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

