#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define ONESHOT_TAP_TOGGLE 2

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 3000

#define PERMISSIVE_HOLD

#define COMBO_TERM 25

#undef RGB_MATRIX_HUE_STEP
#define RGB_MATRIX_HUE_STEP 4

#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_MODIFIERS
#define USB_POLLING_INTERVAL_MS 10
#define SERIAL_NUMBER "jmBzJ/JaRd0Z"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 19

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

#define COMBO_ONLY_FROM_LAYER 1

